import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
	plugins: [
		{
			name: 'copy-static-files',
			setup(build) {
				build.onEnd(async () => {
					const fs = await import('fs/promises');
					try {
						await fs.copyFile('manifest.json', 'dist/manifest.json');
						await fs.copyFile('styles.css', 'dist/styles.css');
						console.log('Copied manifest.json and styles.css to dist/');
					} catch (e) {
						console.error('Failed to copy static files:', e);
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
